# Site Settings
name: DevelopersPoint
title: Home | DevelopersPoint Blog
description: DevelopersPoint is an open source student run club
tags:
  - blog
  - developerspoint
  - opensource
  - studentclub
  - nitap
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: contact@developerspoint.org
disqus_username: https-blog-developerspoint-org
comments: true

disqus:
  comments: true  # boolean type, the global switch for posts comments.
  shortname: 'https-blog-developerspoint-org'    # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname

# Social Media Settings
# Remove the item if you don't need it
github_username: developerspoint-org
facebook_username: developerspoint-org
twitter_username: developerspoint-org
instagram_username: developerspoint-org
linkedin_username: developerspoint-org
medium_username: developerspoint-org


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.developerspoint.org" # the base hostname & protocol for your site
google_analytics: "G-ZDW4M02W4C"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md'
]

# Theme
version: v3.1.0
