name: DevelopersPoint
title: DevelopersPoint | Developers Point
description: DevelopersPoint is an open source student run club
tags:
  - blog
  - developerspoint
  - opensource
  - studentclub
  - nitap
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  #- title: Feed
  #  url: /feed.xml
email: contact@developerspoint.org
disqus_username: developerspoint-org
